### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dodacvan** [degaray/openpay-magento2-module#24]
in di.xml file couldn't found Openpay\Client.

**Comment by dodacvan** [comment]
Go to checkout page and get this error.
I installed on M 2.0.4

`
Fatal error: Uncaught exception 'Magento\Framework\Exception\LocalizedException' with message 'Source class "\Openpay\Client\Mapper\OpenpayCustomer" for "Openpay\Client\Mapper\OpenpayCustomerMapper" generation does not exist.' in C:\xampp\htdocs\magento22\vendor\magento\framework\Code\Generator.php:171 Stack trace: #0 C:\xampp\htdocs\magento22\vendor\magento\framework\Code\Generator.php(100): Magento\Framework\Code\Generator->tryToLoadSourceClass('Openpay\\Client\\...', Object(Magento\Framework\Api\Code\Generator\Mapper)) #1 C:\xampp\htdocs\magento22\vendor\magento\framework\Code\Generator\Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Openpay\\Client\\...') #2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Openpay\\Client\\...') #3 [internal function]: spl_autoload_call('Openpay\\Client\\...') #4 C:\xampp\htdocs\magento22\vendor\magento\framework\ObjectManager\Relations\Runtime.php(38): class_exists('Openpay\\Client\\...') #5 C:\xampp\htdocs\magento22\vendor\magento\framewor in C:\xampp\htdocs\magento22\vendor\magento\framework\Code\Generator.php on line 171
`

**Comment by degaray** [comment]
Hi where you able to fix it?

**Comment by degaray** [comment]
This module is intended for web API only at the moment.
